backend:
  name: git-gateway # Dies ist korrekt für Netlify
  branch: main      # Dein Haupt-Branch (wahrscheinlich 'main' oder 'master')

publish_mode: editorial_workflow # Optional, aber empfehlenswert
media_folder: "images"           # MUSS zu deinem GitHub-Ordnernamen passen
public_folder: "/images"         # MUSS zu deinem GitHub-Ordnernamen passen

# Definition der Collections (File Collection zum Bearbeiten einer einzelnen JSON-Datei)
collections:
  - name: "immobilien_verwaltung"
    label: "Immobilien Verwaltung"
    files:
      - file: "immobilien.json"
        label: "Immobilien Liste"
        name: "immobilien_liste"
        fields:
          # Root-Feld: Die Liste der Immobilien, die das Array in der JSON darstellt
          - label: "Alle Immobilien-Einträge"
            name: "items"
            widget: "list"
            summary: "{{fields.titel}} in {{fields.stadt}}"
            fields:
              # Einzelne Felder für jedes Immobilien-Objekt
              - { label: "Titel", name: "titel", widget: "string", required: true }
              - { label: "Stadt", name: "stadt", widget: "string", required: true }
              - { label: "Zimmer", name: "zimmer", widget: "number", min: 1, required: true }
              - { label: "Größe (qm)", name: "groesse_qm", widget: "number", min: 10, required: true }
              - { label: "Kaufpreis (€)", name: "kaufpreis", widget: "number", min: 10000, required: true }
              - { label: "Bild-URL", name: "bild_url", widget: "image", required: true }
              
              # FINALE DEFINITION FÜR KEY FACTS (als Liste von Strings)
              - label: "Key Facts"
                name: "key_facts"
                widget: "list"
                # Erstellt einen String-Array, der wie erwartet in JSON gespeichert wird
                field: { label: "Fakt", name: "fakt", widget: "string" }