backend:
  name: git-gateway
  branch: main
  
publish_mode: editorial_workflow
media_folder: "bilder"
public_folder: "/bilder"

# WICHTIG: Verwende 'files' anstelle von 'collections' und verschachtele die Felder korrekt.
# Die Hauptstruktur ist eine Liste von "files", nicht eine Liste von "collections".

collections:
  - name: "daten"
    label: "Immobilien Daten"
    files:
      - file: "immobilien.json" # Zielt auf die Datei im Root-Verzeichnis
        label: "Immobilien Liste"
        name: "immobilien_liste"
        fields:
          # Das Widget 'list' erstellt das Array, das dein Skript erwartet
          - label: "Immobilien-Einträge"
            name: "items"
            widget: "list"
            summary: "{{fields.titel}} ({{fields.stadt}})"
            fields:
              # Deine einzelnen Immobilienfelder:
              - {label: "Titel", name: "titel", widget: "string"}
              - {label: "Stadt", name: "stadt", widget: "string"}
              - {label: "Zimmeranzahl", name: "zimmer", widget: "number", min: 1}
              - {label: "Kaufpreis (€)", name: "kaufpreis", widget: "number", min: 10000}
              - {label: "Bild", name: "bild_url", widget: "image"} # Widget 'image' für den Upload
              - label: "Key Facts"
                name: "key_facts"
                widget: "list"
                field: {label: Fact, name: fact, widget: string}