backend:
  name: git-gateway
  branch: main # oder master, je nach deinem Hauptbranch    # WICHTIG: Nutze 'test-repo' für lokale Tests, um Login zu umgehen

media_folder: "bilder"
public_folder: "/bilder"

# Definition der Collections (eine Liste von Dateien)
collections:
  - name: "immobilien_verwaltung"
    label: "Immobilien Verwaltung"
    files:
      - file: "immobilien.json"
        label: "Immobilien Liste"
        name: "immobilien_liste"
        fields:
          # Root-Feld: Die Liste der Immobilien, die das Array in der JSON darstellt
          - label: "Alle Immobilien-Einträge"
            name: "items"
            widget: "list"
            summary: "{{fields.titel}} in {{fields.stadt}}"
            fields:
              # Einzelne Felder für jedes Immobilien-Objekt
              - {label: "Titel", name: "titel", widget: "string", required: true}
              - {label: "Stadt", name: "stadt", widget: "string", required: true}
              - {label: "Zimmer", name: "zimmer", widget: "number", min: 1, required: true}
              - {label: "Größe (qm)", name: "groesse_qm", widget: "number", min: 10, required: true}
              - {label: "Kaufpreis (€)", name: "kaufpreis", widget: "number", min: 10000, required: true}
              - {label: "Bild-URL", name: "bild_url", widget: "image", required: true}
              - label: "Key Facts (pro Zeile)"
                name: "key_facts"
                widget: "list"
                field: {label: Fact, name: fact, widget: string, required: true}